### ISSUE TITLE
Unable to configure docker for clickable

### ISSUE THREAD

**Issue by Jujuyeh** [bhdouglass/clickable#75]
I've tried installing clickable via AUR and via Pip+Git. Both ways gave me errors at post-setup when running `clickable setup-docker`.

This is the output I get:

```
Traceback (most recent call last):
  File "/usr/bin/clickable", line 11, in <module>
    load_entry_point('clickable==4.3.3', 'console_scripts', 'clickable')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/clickable/__init__.py", line 6, in <module>
    from clickable.build_templates.cmake import CMakeClickable
ModuleNotFoundError: No module named 'clickable.build_templates'
```

**Comment by bhdouglass** [comment]
The AUR package should soon be fixed (as per #72), and the pip+git method you'll have to use the clickable-dev command for now.

**Comment by Jujuyeh** [comment]
When I run `clickable-dev setup-docker` I get:

```
Traceback (most recent call last):
  File "/usr/bin/clickable-dev", line 3, in <module>
    import clickable
  File "/usr/lib/python3.6/site-packages/clickable/__init__.py", line 6, in <module>
    from clickable.build_templates.cmake import CMakeClickable
ModuleNotFoundError: No module named 'clickable.build_templates'
```

**Comment by bhdouglass** [comment]
Is this via AUR or pip?

**Comment by Jujuyeh** [comment]
That was via AUR.

Via pip doesn't find `clickable-dev` command.

**Comment by bhdouglass** [comment]
Ok, try pip again, I just included a fix

**Comment by bhdouglass** [comment]
Awesome! Then I'll close this issue and leave #72 open for fixing the arch package
